import type { KanaVoiceType } from '../types/kana.js'
import type { NodeState } from './srs.js'

/**
 * 中文 UI 文案集中（架构 §2.2 / §8.6）。
 *
 * 本期不引入 i18n 运行时：界面为中文静态文案，日语为**数据内容**（来自 JSON）。
 * 所有页面 / 组件不得硬编码中文，一律引用本文件，便于未来替换为 i18n 调用点。
 */
export const STRINGS = {
  app: {
    name: 'JLPT N3 単語',
    loading: '正在恢复学习进度…',
  },
  common: {
    confirm: '确认',
    cancel: '取消',
    back: '返回',
    next: '下一张',
    prev: '上一张',
    skip: '跳过',
    flip: '看释义',
    flipBack: '看假名',
    empty: '暂无内容',
    times: '次',
  },
  tts: {
    tapToSpeak: '点击卡片发音',
    replay: '再听一次',
    unsupportedTitle: '当前环境不支持语音',
    unsupportedBody:
      '当前运行环境不支持日语语音合成，请用「复制假名」自行朗读。',
    noJaVoice: '当前环境缺少日语语音包，已降级为「复制假名」。',
    blocked: '首次播放需在点击内触发，请再点一次「试听」。',
    serviceDown: '语音服务暂时不可用，已尝试系统语音；仍无声请用「复制假名」。',
    serviceRejected:
      '语音服务拒绝了本次请求（参数或语种异常），请用「复制假名」。',
    noPlayer: '当前环境没有可用的音频播放器，请用「复制假名」。',
    error: '语音播放失败，请重试或使用「复制假名」。',
    copyKana: '复制假名',
    copied: '假名已复制到剪贴板',
    copyFallback: '当前环境无剪贴板权限，假名如下，请手动复制',
    copyTitle: '假名',
  },
  nodeState: {
    locked: '未解锁',
    未学: '未学',
    学习中: '学习中',
    模糊: '模糊',
    已掌握: '已掌握',
    需强化: '需强化',
  } satisfies Record<NodeState, string>,
  home: {
    greeting: '欢迎回来',
    todayGoal: '今日任务',
    newLearned: '新学',
    reviewed: '复习',
    grammarLearned: '语法',
    streak: '连续打卡',
    dayUnit: '天',
    dueToday: '今日到期',
    continueLearning: '继续学习',
    startLearning: '开始学习',
    weakWarning: '薄弱预警',
    weakEmpty: '暂无薄弱词条',
    stageProgress: '阶段进度',
    graphEntry: '知识图谱',
    noSessionHint: '还未开始学习，从第一个模块开始吧',
    sprintHint: '冲刺期以复习与自测为主',
  },
  stage: {
    title: '阶段地图',
    subtitle: '按顺序解锁：上一含词阶段完成度达标后开放',
    module: '模块',
    wordCount: '词',
    wordCountUnit: '词',
    lockedHint: '需上一含词阶段完成度 ≥ 80%',
    sprintTitle: '冲刺期',
    sprintBody:
      '本阶段无词条内容，完成度不参与计算（冲刺期以复习与自测为主）。',
    unlockRuleOff: '解锁规则已在设置中关闭',
    ruleLabel: '解锁规则',
    ruleToggleOn: '已开启',
    ruleToggleOff: '已关闭',
    weekLabel: '备考周',
  },
  study: {
    title: '词汇学习',
    reviewTitle: '复习模式',
    emptyModule: '该模块暂无词条',
    webFallbackHint: '可左右滑动或点按「上一张 / 下一张」翻页',
    cardProgress: '卡片进度',
    moduleDoneTitle: '本模块已学完',
    moduleDoneBody: '本模块词条已全部掌握，可以继续下一模块。',
    stageDoneTitle: '本阶段已完成',
    stageDoneBody: '本阶段完成度已达标，下一阶段已解锁。',
    viewGraph: '查看知识图谱',
    nextModule: '继续下一模块',
    backToStages: '返回阶段地图',
    selfEvalUnknown: '不认识',
    selfEvalVague: '模糊',
    selfEvalKnown: '认识',
    detailedEntry: '进入详解',
    sessionWrong: '本次答错',
  },
  detailSheet: {
    autoTitle: '第一次遇到这个词',
    autoBody: '要不要看看它的详解？',
    promptTitle: '连续答错了',
    promptBody: '建议先看详解，再继续学习。',
    confirm: '查看详解',
    dismiss: '忽略，继续',
  },
  vocab: {
    title: '词汇详解',
    kana: '读音',
    pos: '词性',
    meaning: '释义',
    conjugation: '动词变形',
    related: '关联词',
    sentences: '例句',
    memory: '记忆状态',
    wrongCount: '累计答错',
    noSentences: '暂无例句',
    notFound: '未找到该词条',
    form: '形',
  },
  review: {
    title: '复习',
    dueTitle: '今日到期',
    weakTitle: '错词本',
    dueCount: '待复习',
    start: '开始复习',
    dueEmpty: '今日没有到期内容',
    weakEmpty: '暂无错词，继续保持！',
  },
  grammarList: {
    title: '语法列表',
    filterWeek: '周次',
    filterLevel: '层级',
    all: '全部',
    empty: '暂无语法点',
    weekLabel: '周',
    countUnit: '条',
  },
  grammarDetail: {
    title: '语法详解',
    connection: '接续',
    scene: '场景',
    examples: '例句',
    related: '近义辨析',
    words: '涉及词汇',
    mastery: '掌握度自评',
    notFound: '未找到该语法点',
    emptyExamples: '暂无例句',
    emptyRelated: '暂无关联语法',
    emptyWords: '暂无涉及词汇',
  },
  graph: {
    title: '知识图谱',
    viewOverview: '全景',
    viewWord: '词条',
    viewGrammar: '语法',
    reset: '重置',
    zoomIn: '放大',
    zoomOut: '缩小',
    focusHint: '点击节点聚焦，再次点击进入；点空白取消聚焦',
    empty: '暂无图谱数据',
    enter: '进入详情',
    legendStage: '阶段',
    legendModule: '模块',
    legendWord: '词条',
    legendGrammar: '语法',
  },
  quiz: {
    title: '自测',
    modeJaZh: '日→中',
    modeZhJa: '中→日',
    modeListen: '听音选词',
    promptJaZh: '请选择正确释义',
    promptZhJa: '请选择正确假名',
    promptListen: '请选择听到的词',
    listen: '播放发音',
    correct: '回答正确',
    wrong: '回答错误',
    next: '下一题',
    finish: '看结果',
    done: '本轮完成',
    score: '得分',
    restart: '再测一次',
    empty: '暂无可出题的词条',
    progressLabel: '题目',
    answerLabel: '正确答案',
    back: '返回',
  },
  me: {
    title: '我的',
    pronunciation: '发音设置',
    rate: '语速',
    pitch: '音调',
    autoSpeak: '卡片出现即读',
    preview: '试听',
    previewText: 'こんにちは',
    on: '开',
    off: '关',
    unlockSection: '解锁规则',
    unlockRule: '阶段解锁限制',
    statsSection: '学习统计',
    statTotalWords: '词条总数',
    statSeen: '已学',
    statMastered: '已掌握',
    statWeak: '需强化',
    statGrammar: '语法点',
    todayNew: '今日新学',
    todayReview: '今日复习',
    todayGrammar: '今日语法',
    dataSection: '数据管理',
    exportData: '导出数据（JSON）',
    exportHint: '点击生成并复制学习数据 JSON',
    exported: '已复制到剪贴板',
    exportFailed: '当前环境无法复制，文本见下方',
    resetData: '清空学习进度',
    resetConfirm: '再次点击确认清空',
    resetDone: '已清空',
  },
  kana: {
    title: '五十音图',
    subtitle: '先认形，再挂词，最后能默写',
    // —— K0 总览 ——
    startEntry: '开始入门',
    continueEntry: '继续入门',
    reviewEntry: '复习错音',
    quizEntry: '本关测验',
    graduationEntry: '开始结业测验',
    graduationTitle: '假名基础已达标',
    graduationBody: '12 关全部掌握。可以开始 N5 词汇学习了。',
    goVocab: '进入 N5 词汇',
    gateHint: '先完成五十音清音 5 关，再进入词汇学习',
    lockedHint: '需前置关已掌握率 ≥ 80%',
    empty: '暂无五十音数据',
    voicedLabel: '清音 / 浊音 / 半浊音 / 拗音',
    /**
     * 学习模式开关。
     *
     * 语义对齐参考产品：开关**不过滤内容**（不隐藏罗马音、不筛掉已掌握音），
     * 只给音表加高亮描边，把「浏览态」切成「可点学习区」（设计 §5.1）。
     */
    studyModeOn: '学习模式·开',
    studyModeOff: '学习模式·关',
    studyModeHint: '开启后可点音格进入学习；关闭时仅浏览',
    groupUnit: '关',
    /** 12 关列表的小标题。 */
    groupSection: '关卡进度',
    kanaUnit: '音',
    overallLabel: '总进度',
    studyEntry: '进入学习',
    /** 首页假名卡上的次级入口（进入 K0 看音表）。 */
    openTable: '查看音表',
    // —— 音表 ——
    scriptHiragana: '平假名',
    scriptKatakana: '片假名',
    scriptRomaji: '罗马音',
    columnHeader: '段',
    /** 音表行首标签后缀（`${行首假名}${rowSuffix}` → 「あ行」）。 */
    rowSuffix: '行',
    /** 音类主 Tab 的文案。 */
    voiceLabels: {
      清音: '清音',
      浊音: '浊音',
      半浊音: '半浊音',
      拗音: '拗音',
    } satisfies Record<KanaVoiceType, string>,
    // —— K1 学习卡 ——
    studyTitle: '假名学习',
    reviewTitle: '错音复习',
    cardProgress: '卡片进度',
    originHiragana: '平假名字源',
    originKatakana: '片假名字源',
    derivationLabel: '构成来源',
    derivationDaku: '＋浊点 ゛',
    derivationHandaku: '＋半浊点 ゜',
    derivationYoon: '＋小写 ゃ / ゅ / ょ',
    examples: '应用实例',
    inWordList: '已在词表',
    confusable: '易混对比',
    writing: '书写练习区',
    writingHint: '在半透明字形上描红；写错了清空重来',
    clearCanvas: '清空',
    memoryMode: '默写',
    memoryOn: '默写中',
    memoryOff: '描红中',
    peek: '不会写，偷看一眼',
    peekHint: '遮盖会在 2 秒后自动恢复',
    prevKana: '上一个',
    nextKana: '下一个',
    groupDoneTitle: '本关已学完',
    groupDoneBody: '本关假名已全部掌握，来一轮测验巩固吧。',
    startQuiz: '开始本关测验',
    nextGroup: '继续下一关',
    backToKana: '返回五十音',
    skipKana: '跳过',
    // —— K2 测验 ——
    quizTitle: '假名测验',
    quizProgress: '题目',
    quizPromptListen: '请选择听到的假名',
    quizPromptKanaToRomaji: '请选择正确罗马音',
    quizPromptRomajiToKana: '请选择正确假名',
    quizPromptScriptSwapToKatakana: '请选择对应的片假名',
    quizPromptScriptSwapToHiragana: '请选择对应的平假名',
    quizPromptTypeRomaji: '请输入罗马音',
    quizInputPlaceholder: '输入罗马音后确认',
    quizTypeRomajiHint: '支持 し=shi/si、つ=tsu/tu 等常见写法',
    quizSubmit: '确认',
    quizCorrect: '回答正确',
    quizWrong: '回答错误',
    quizAnswer: '正确答案',
    quizNext: '下一题',
    quizFinish: '看结果',
    quizDone: '本关测验完成',
    quizScore: '得分',
    quizRestart: '再测一次',
    quizEmpty: '本关暂无可出题内容',
    quizListen: '播放发音',
    quizBack: '返回五十音',
    // —— K3 复习（并入 P7）——
    reviewDueTitle: '假名到期',
    reviewDueEmpty: '今日没有到期假名',
    reviewWeakTitle: '错音本',
    reviewWeakEmpty: '暂无错音，继续保持！',
    reviewConfusableTitle: '易混对比',
    reviewConfusableEmpty: '暂无易混错音',
    reviewStart: '开始假名复习',
    reviewPairTimes: '累计错',
    // —— P9 设置 ——
    settingsSection: '假名基础',
    settingsGate: '入门门控',
    settingsGateHint: '开启后，五十音清音 5 关达标前首页主按钮指向五十音',
    settingsReset: '清空假名进度',
    settingsResetConfirm: '再次点击确认清空假名进度',
    settingsResetDone: '假名进度已清空',
    // —— 主链路衔接（P1 阶段地图树顶节点）——
    nodeTitle: 'K · 五十音入门',
    nodeMeta: 'N5 词汇的前置能力',
    // —— P3 词汇详解的「拆音」——
    splitKana: '拆音',
    splitHint: '点音格去复习这个音（っ / ー 不单独成音）',
    gateBadge: '假名基础已达标',
  },
} as const

export type Strings = typeof STRINGS
